### PR TITLE
[ISSUE #1006] Update the instruction docs (CN)

### PR DESCRIPTION
**Pull request by kirinzhu**
Fixes ISSUE #1006 .

### Motivation
The instruction docs need to be updated

### Modifications

Update the instruction docs (CN)

### Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by xiaoyang-sde** [comment]
I think the English instruction docs are up-to-date but Chinese instruction docs are outdated. I guess we could translate the English docs to Chinese?

**Comment by xiaoyang-sde** [comment]
The number before the file name (e.g. **`01`**`-store.md`) is the order of the pages in the website sidebar. I suggest that we could avoid using duplicated numbers.

**Comment by kirinzhu** [comment]
Oops, sorry, I will modify the index number.
installation:  The installation docs (CN) is updated now, and I am working on the English version.
design-document: The design-document (EN) is complete and detailed, maybe we can translate it into Chinese version.

On Jul 8, 2022, at 11:01 AM, Xiaoyang Liu ***@***.******@***.***>> wrote:



The number before the file name (e.g. 01-store.md) is the order of the pages in the website sidebar. I suggest that we could avoid using duplicated numbers.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Pull request merged**
