### PR TITLE
[ISSUE #3053] configuration file does not exist

### LINKED ISSUE #2935: [Bug] Failed to address the resource file from within Jar as a File
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

When I run the latest master code, the program cannot read the Prometheus configuration file. 

I found [L137-L140](https://github.com/apache/incubator-eventmesh/blob/0a13020172e2d608754c3041ef761b207ccbaf1c/eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java#L137-L140) Failed to address the resource file from within Jar as a File, instead, [getResourceAsStream](http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getResourceAsStream%28java.lang.String%29) should be used. 

ref: https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar

### How to reproduce

Just run the master code. 

### Debug logs

```
2023-01-19 20:33:52,804 INFO  [main] EventMeshTcpRetryer(EventMeshTcpRetryer.java:102) - EventMeshTcpRetryer inited......
2023-01-19 20:33:52,807 INFO  [main] MetaInfExtensionClassLoader(MetaInfExtensionClassLoader.java:77) - load extension class success, extensionType: interface org.apache.eventmesh.metrics.api.MetricsRegistry, extensionClass: class org.apache.eventmesh.metrics.prometheus.PrometheusMetricsRegistry
2023-01-19 20:33:52,812 pool-1-thread-1 DEBUG Stopping LoggerContext[name=73d16e93, org.apache.logging.log4j.core.LoggerContext@342c38f8]
2023-01-19 20:33:52,812 pool-1-thread-1 DEBUG Stopping LoggerContext[name=73d16e93, org.apache.logging.log4j.core.LoggerContext@342c38f8]...
2023-01-19 20:33:52,808 ERROR [main] EventMeshStartup(EventMeshStartup.java:56) - EventMesh start fail.
java.lang.RuntimeException: file is not exists
	at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:139) ~[eventmesh-common-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.common.config.ConfigService.populateConfig(ConfigService.java:168) ~[eventmesh-common-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.common.config.ConfigService.populateConfigForObject(ConfigService.java:113) ~[eventmesh-common-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.spi.EventMeshExtensionFactory.lambda$getSingletonExtension$0(EventMeshExtensionFactory.java:91) ~[eventmesh-spi-1.7.0-release.jar:1.7.0-release]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_291]
	at org.apache.eventmesh.spi.EventMeshExtensionFactory.getSingletonExtension(EventMeshExtensionFactory.java:84) ~[eventmesh-spi-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.spi.EventMeshExtensionFactory.getExtension(EventMeshExtensionFactory.java:77) ~[eventmesh-spi-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.metrics.api.MetricsPluginFactory.getMetricsRegistry(MetricsPluginFactory.java:38) ~[eventmesh-metrics-api-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.lambda$null$1(EventMeshTCPServer.java:224) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_291]
	at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.lambda$init$2(EventMeshTCPServer.java:223) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_291]
	at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.init(EventMeshTCPServer.java:222) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshTcpBootstrap.init(EventMeshTcpBootstrap.java:50) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshServer.init(EventMeshServer.java:108) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshServer.<init>(EventMeshServer.java:83) ~[eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:38) [eventmesh-runtime-1.7.0-release.jar:1.7.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]
```

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #3053: [Bug] configuration file does not exist
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

I failed to start in standalone mode

### How to reproduce

1. add env properties
```
-Dlog4j.configurationFile=eventmesh-runtime/conf/log4j2.xml
-Deventmesh.log.home=eventmesh-runtime/logs
-Deventmesh.home=eventmesh-runtime
-DconfPath=eventmesh-runtime/conf
```

2. run starter

### Debug logs

```
java.lang.RuntimeException: configuration file does not exist
	at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:142) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.common.config.ConfigService.setRootConfig(ConfigService.java:69) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:36) [eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]
> Task :eventmesh-starter:StartUp.main() FAILED
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by koonchen**
Fixes #3053 

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

I failed to start in standalone mode with macos 11 and i found a similar issue #2935 that still unresolved.
So i try it myself.

```shell
2023-02-02 11:09:36,157 ERROR [main] EventMeshStartup(EventMeshStartup.java:56) - EventMesh start fail.
java.lang.RuntimeException: file is not exists
  at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:139) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.common.config.ConfigService.populateConfig(ConfigService.java:168) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.common.config.ConfigService.populateConfigForObject(ConfigService.java:113) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.spi.EventMeshExtensionFactory.lambda$getSingletonExtension$0(EventMeshExtensionFactory.java:91) ~[eventmesh-spi-1.8.0-release.jar:1.8.0-release]
  at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_312]
  at org.apache.eventmesh.spi.EventMeshExtensionFactory.getSingletonExtension(EventMeshExtensionFactory.java:84) ~[eventmesh-spi-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.spi.EventMeshExtensionFactory.getExtension(EventMeshExtensionFactory.java:77) ~[eventmesh-spi-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.metrics.api.MetricsPluginFactory.getMetricsRegistry(MetricsPluginFactory.java:38) ~[eventmesh-metrics-api-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.lambda$null$1(EventMeshTCPServer.java:223) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
  at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.lambda$init$2(EventMeshTCPServer.java:222) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_312]
  at org.apache.eventmesh.runtime.boot.EventMeshTCPServer.init(EventMeshTCPServer.java:221) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.runtime.boot.EventMeshTcpBootstrap.init(EventMeshTcpBootstrap.java:50) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.runtime.boot.EventMeshServer.init(EventMeshServer.java:108) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.runtime.boot.EventMeshServer.<init>(EventMeshServer.java:83) ~[eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:38) [eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
  at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]

> Task :eventmesh-starter:StartUp.main() FAILED
65 actionable tasks: 3 executed, 62 up-to-date
```

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by koonchen** [comment]
PTAL

**Comment by horoc** [comment]
hi @koonchen, it seems there is another PR #2966 which is trying to fix this issue.  @sbmvirdi, are you still working on it?

**Comment by sbmvirdi** [comment]
yes actually i was trying to fix the issue but was not able to getting some test cases failure @koonchen is this fixed by your end ?

**Comment by koonchen** [comment]
@sbmvirdi I have solved this problem without any additional problems, this issue #2935 has been open for a while, please accept my PR and close the issue :)

**Comment by xwm1992** [comment]
> @sbmvirdi I have solved this problem without any additional problems, this issue #2935 has been open for a while, please accept my PR and close the issue :)

Hi @koonchen, thank you for your contribute first, but this issue #2935 has been assigned to the @sbmvirdi , please confirm whether the issue has been asigned to others before submitting pr, thanks.

**Comment by koonchen** [comment]
@xwm1992 Yes, you are right, I didn't express my meaning clearly, this PR #2966 didn't solve my problem, I still get an error when I use the latest master.

```
java.lang.RuntimeException: configuration file does not exist
	at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:142) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.common.config.ConfigService.setRootConfig(ConfigService.java:69) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:36) [eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]
> Task :eventmesh-starter:StartUp.main() FAILED
```

I mean just modifying this line of code is not enough `InputStream configurationInputStream = getClass().getResourceAsStream(filePath);`

**Comment by koonchen** [comment]
link #3053

**Comment by koonchen** [comment]
Closes #3053

**Comment by koonchen** [comment]
@horoc @xwm1992 I don't know how to relate to the new issue #3053, please help to see if the issue needs to be fixed, thx :)

**Review by xwm1992 — APPROVED** [review]

**Comment by HattoriHenzo** [comment]
@xwm1992 seems like the change is not available in the master branch. I am also facing the same issue, while trying to start the project.

**Pull request merged**
