### PR TITLE
[ISSUE #1072] Extraction of constants [WebHookOperationConstant]

### LINKED ISSUE #1072: [Enhancement] Extraction of constants [WebHookOperationConstant]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image

### Describe the solution you'd like

Located at:eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java
Extract the constants from the image to this class.
Will "System. GetProperty (" confPath", System. The getenv (" confPath ")) "to" eventmesh - common/SRC/main/Java/org/apache/eventmesh/common/Constants "Constants of replacement.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by soundarrajan-official**
Fixes #1072 

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by xwm1992** [comment]
@soundarrajan-official hi, for the first time contributor , please make sure the committs which you submitted is associate with your github email not others, such as the pic below:
企业微信截图_16660769258148

**Comment by soundarrajan-official** [comment]
@xwm1992 I am not sure how it happened, Next time take care of it.

So is my PR will accept or not if it reviewed ?

**Comment by xwm1992** [comment]
> @xwm1992 I am not sure how it happened, Next time I will take care of it.
> 
> So is my PR will accept or not if it reviewed ?
> 
> Do I need to do any changes or not ?

you just need to confirm what I indicated above, the email, because I can't see your email at here, only code submitter can check this in your local committ record.

**Comment by soundarrajan-official** [comment]
> 

Screenshot 2022-10-18 at 1 02 17 PM

**Comment by xwm1992** [comment]
> > 
> 
> Screenshot 2022-10-18 at 1 02 17 PM

make sure `soundarrajan.official@gmail.com` is your github account gmail is ok.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Comment by soundarrajan-official** [comment]
> > > 
> > 
> > 
> > Screenshot 2022-10-18 at 1 02 17 PM
> 
> make sure `soundarrajan.official@gmail.com` is your github account gmail is ok.

Yes It's my github account only, Thank You

**Pull request merged**
