### PR TITLE
[ISSUE #1194] Fix FileWebHookConfigOperation insert error

### PR DESCRIPTION
**Pull request by horoc**
Fix FileWebHookConfigOperation insert error

### Motivation

#1194 

### Modifications

- Fix the FileLock release exception.
- Fix queryWebHookConfigByManufacturer iterating condition, ```endIndex``` should be the inclusive bound.
- Add unit test of insertWebHookConfig  

### Documentation

None

### CODE REVIEW

**Review by qqeasonchen — DISMISSED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@horoc there are fail CI taslks needed to be fixed before merged.

**Comment by qqeasonchen** [comment]
@horoc please check the CI fail tasks.

**Comment by horoc** [comment]
> @horoc please check the CI fail tasks.

Fixed, please help to review the changes, lots of thanks.

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Pull request merged**
