### PR TITLE
[ISSUE #1205] Fix bugs in Kafka Producer and Minimum Viable Kafka Consumer

### LINKED ISSUE #1205: [Enhancement] Fix the Kafka Consumer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The Kafka Consumer is not yet fully implemented

### Describe the solution you'd like

Implement the Kafka Consumer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Markliniubility**
Fixes #1205.

### Motivation

*Complete the support for Kafka Connector*

### Modifications

*Fix bugs in Kafka Producer*
*Implemented a Minimum Viable Kafka Consumer*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- Yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- It will be documented after its completion and rollout in a separate PR

### CODE REVIEW

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@Markliniubility please check the CI fail tasks.

**Comment by Markliniubility** [comment]
> @Markliniubility please check the CI fail tasks.

Thanks! I was mostly about checkstyle that fails I believe. Will fix the formating tomorrow!

**Comment by qqeasonchen** [comment]
I let it merge first, you can fix it when merge to master.

**Pull request merged**
