### PR TITLE
[ISSUE #1090] Support for managing EventMesh events using AsyncAPI

### LINKED ISSUE #1090: [Feature] Support for managing EventMesh events using AsyncAPI
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

1. Implement EventMesh Catalog to manage AsyncAPI
2. Applications can define events through AsyncAPI and register with EventMesh Catalog
3. Application uses AsyncAPI to Pub/Sub events

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by walterlife**
Fixes #1090 

### Motivation
add eventmesh-catalog module,support for managing EventMesh events using AsyncAPI

### Modifications
add eventmesh-catalog-go module。

### Documentation
+ Does this pull request introduce a new feature? (yes / no)
+ If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
+ If a feature is not applicable for documentation, explain why?
+ If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by walleliu1016** [comment]
I have no problem with the PR, but it would be better to add some more test cases for each go file.

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Comment by walterlife** [comment]
> 

Yes, I will add UT under unity after the overall core code is complete

**Comment by walterlife** [comment]
> 

@walleliu1016 
Yes, I will add UT under unity after the overall core code is complete

**Comment by walterlife** [comment]
> 



> I have no problem with the PR, but it would be better to add some more test cases for each go file. The main function is empty @walterlife

Yes, I will add UT under unity after the overall core code is complete

**Pull request merged**
