### PR TITLE
[ISSUE #1720]Use stringBuilder instead of string in RedirectClientByIpPortHandler

### LINKED ISSUE #1720: [Enhancement] Method concatenates strings using + in a loop [RedirectClientByIpPortHandler]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandler.java line 82 83
analysis and explanation:
The method seems to be building a String using concatenation in a loop. In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.

### Describe the solution you'd like

Use the StringBuilder, append() method instead.
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by DeepikaMarthandanTW**
Fixes #1720.

### Motivation

In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.

### Modifications

Converted string to string builder

### Documentation

- Does this pull request introduce a new feature? (yes / no) no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by qqeasonchen — DISMISSED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@DeepikaMarthandanTW Please fix the conflicts.

**Comment by xwm1992** [comment]
@DeepikaMarthandanTW there's no file has been changed ?

**Comment by DeepikaMarthandanTW** [comment]
> @DeepikaMarthandanTW there's no file has been changed ?

Yes, this issue has been fixed by @SunnyBoy-WYH

**Comment by xwm1992** [comment]
> > @DeepikaMarthandanTW there's no file has been changed ?
> 
> Yes, this issue has been fixed by @SunnyBoy-WYH

Ok, I'll close this pr.

**Pull request closed without merging**
