### PR TITLE
Inefficient Usage of Java Collection

### PR DESCRIPTION
**Pull request by FastAtlas**
Hi,

This issue is supplementary to #517. We change the patches from `master` branch to `develop` branch. 

We find that there are other inefficient usages of Java Collections:

1. The contains method is invoked upon a list object in a loop. We recommend replacing it with a HashSet.
Random access can occur at several LinkedList objects, which run in linear time complexity. We recommend replacing them with Arraylist objects.
2. ArrayList is inserted before an iteration, while multiple memory reallocation might occur when the size of the list exceeds its capacity. We recommend replacing it with a LinkedList.
3. LinkedList is not inefficient when we perform random access upon it. We recommend replacing it with an ArrayList.

We discovered the above inefficient usage of containers by our tool Ditto. The patch is submitted. Could you please check and accept it? We have tested the patch on our PC. The patched program works well.

Bests

Ditto

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by DittoTool** [comment]
> LGTM

Thank you for your confirmation.

**Review by SteveYurongSu — APPROVED** [review]
LGTM

**Review by Shoothzj — APPROVED** [review]

**Comment by ruanwenjun** [comment]
@FastAtlas Hi, sorry to leave this pr too long and there are some conflicts, please solve this.

**Comment by ruanwenjun** [comment]
Close due to no response.

**Pull request closed without merging**
