### PR TITLE
Update codeStyle.xml

### PR DESCRIPTION
**Pull request by qqeasonchen**

### CODE REVIEW

**Review by jonyangx — APPROVED** [review]
It looks good!

**Review by keranbingaa — COMMENTED** [review]
string "defibus" can be find in eventmesh-connector-rocketmq, gradle.properties,it can be modified together

**Comment by qqeasonchen** [comment]
> string "defibus" can be find in eventmesh-connector-rocketmq, gradle.properties,it can be modified together

gradle.properties of all the moudles have defibus, we can start a new PR to fix this.

**Review by keranbingaa — APPROVED** [review]
ok,I think this pr can be merged

**Pull request merged**
