### PR TITLE
[ISSUE #340]Integrate With OpenTelemetry

### PR DESCRIPTION
**Pull request by Roc-00**
Fixes ISSUE#<340>.

### Motivation

Export metrics data with open telemetry and use Prometheus for visual observation

### Modifications

There is a readme document in the code I submitted. I use idea to run locally. I download Prometheus in the window version of the official website. The operation method of docker written in readme is given by reference to open telemetry. I haven't actually operated it. I was successful in running locally. I'm not sure whether the code I wrote meets the requirements, so I didn't finish all the metrics, but wrote three. If there is anything wrong, please put it forward and I will modify and improve it. When the code is perfect and correct, I will continue to write the rest of the code.

### Documentation

- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented?README.md

### CODE REVIEW

**Comment by Roc-00** [comment]
image
It seems that I did something wrong with PR operation... I have brought up the previous pr. how can I solve it?

**Comment by Roc-00** [comment]
It seems that I did something wrong with PR operation... I have brought up the previous pr. how can I solve it?

**Comment by ruanwenjun** [comment]
> It seems that I did something wrong with PR operation... I have brought up the previous pr. how can I solve it?

@Roc-00 What do you mean? If this pr was submitted accidentally, then you can close it. If you have chosen the wrong branch, then you can edit this pr.

BTW, there already seems to be some interest in this issue #340, if you want to deal with it, you would better describe your plan before submit a pr.

**Comment by Roc-00** [comment]
> > It seems that I did something wrong with PR operation... I have brought up the previous pr. how can I solve it?
> 
> @Roc-00 What do you mean? If this pr was submitted accidentally, then you can close it. If you have chosen the wrong branch, then you can edit this pr.
> 
> BTW, there already seems to be some interest in this issue #340, if you want to deal with it, you would better describe your plan before submit a pr.

image
I'm not sure if I have submitted what I want to submit, because I click in and don't find the content of my file. If the person you mentioned is tydhot, I have asked him for advice.

**Comment by ruanwenjun** [comment]
@Roc-00 You can discuss in this issue #340

**Pull request closed without merging**
