### PR TITLE
[ISSUE #961] Add and update some docs

### PR DESCRIPTION
**Pull request by kirinzhu**
Fixes ISSUE #<961>.

### Motivation

There are missing docs and some docs to be updated

### Modifications

1. Change the directory structures of /docs/
2. Add some missing docs (in Chinese)
3. Update some documents

### CODE REVIEW

**Comment by qqeasonchen** [comment]
good job

**Review by Alonexc — APPROVED** [review]
Is the translation into Chinese not available in the contribution directory under zh, will it be updated later?

**Comment by xwm1992** [comment]
please resolved conflict files.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Pull request merged**
