### PR TITLE
[ISSUE #435] Initial Creation of eventMesh-admin module in EventMesh

### PR DESCRIPTION
**Pull request by yzhao244**
Fixes ISSUE #435 #346

### Motivation

The purpose of this PR is for contributing eventmesh-admin module which includes initial draft of readme file for describing REST APIs

### Modifications

A new eventmesh-admin is created along with a readme file includes REST APIs.

### Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? readme
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Need to discuss, whether we need to add a new control panel module

**Comment by qqeasonchen** [comment]
@yzhao244 Glad to see you again, since this pr is to resolve #435 , i think you can add a new moudle like eventmesh-admin , and schema registry can be another pr.

**Comment by yzhao244** [comment]
@qqeasonchen @ruanwenjun Yes, eventmesh-admin sounds a good idea. I will rework this PR to contribute eventmesh-admin module.

**Comment by qqeasonchen** [comment]
#346 #435 are supposed to included in this pr, but schemaregistry is not.  or you can keep this pr on schemaregistry and launch another one for eventmesh-admin, up to you.

**Comment by yzhao244** [comment]
@qqeasonchen I think you are right. Putting schemaregistry in this pr could be confusing. My thought was that schemaregistry may be a child module of the eventmesh-admin module. Therefore, I defined the schemaregistry REST APIs in the readme file of this commit. :)

**Comment by qqeasonchen** [comment]
@yzhao244 thanks，about schemaregistry, @JunjieChou is working on this too, i suggest we discuss first to decide how to provide service, lonely or in runtime, is it ok? btw, if you have wechat, you can add eventmesh helper or we can have a online meeting.

**Comment by qqeasonchen** [comment]
@yzhao244 @JunjieChou 
Hi, i am trying to make it clear about admin and schemaregistry, so we can move on, if neccessary, we can schedule a meeting :

1. ClientManageController.java can be moved to eventmesh-admin, and add topic/subscriptions management to it.
2. SchemaRegistry is a seperate service out of eventmesh-runtime, eventmesh-schemaregistry can be a moudle in eventmesh, but star itself, not launched by runtime . eventmesh-runtime will interact with schemaregistry using schema-registry-api.

**Comment by yzhao244** [comment]
@qqeasonchen @ruanwenjun @JunjieChou @jinrongluo 
Hi Eason, I agree with you that leaving schema registry out of this PR for sure and yes schema registry can be a seperate service out of eventmesh-runtime.

**Comment by JunjieChou** [comment]
@yzhao244 @qqeasonchen @ruanwenjun 
Hi, I see the discussion here.
From my point of view, I think we can compare schemaregistry to rocketmq. 
What implemented in eventmesh is interactions with rocketmq, while not rocketmq itself. So does schemaregistry.
Anyway, it's my own consideration after referring openschema-spec and may not have taken all things into considerations, the decision is up to you guys with more experience.

**Comment by JunjieChou** [comment]
Currently, I have created a separated running schemaregistry based on springboot. 
Inside such schemaregistry a general skeleton has been completed and most APIs(defined in openschema-spec) have been implemented. 

The left APIs that I haven't accomplished are related to compatibility checks. It is hard and I'm surveying methods for that. 
No matter which type of schemaregistry(separated or inside-eventmesh), compatibility checks are needed. And it will be the main work I am going to do next. 😄

**Comment by yzhao244** [comment]
> Currently, I have created a separated running schemaregistry based on springboot.
> Inside such schemaregistry a general skeleton has been completed and most APIs(defined in openschema-spec) have been implemented.
> 
> The left APIs that I haven't accomplished are related to compatibility checks. It is hard and I'm surveying methods for that.
> No matter which type of schemaregistry(separated or inside-eventmesh), compatibility checks are needed. And it will be the main work I am going to do next. 😄

@qqeasonchen @ruanwenjun @jinrongluo If I am not mistaken, I think it makes sense that schema registry can be run as a seperate service which is out of runtime. Also it can be implemented by using SpringBoot as @JunjieChou is doing.. Therefore, I have removed schema registry APIs out of the readme in eventmesh-admin module and keep this PR only focusing on Admin APIs.

**Comment by qqeasonchen** [comment]
@yzhao244 @JunjieChou sure, for admin module, i think it is clear for us. and for schemaregistry moudle, @JunjieChou is working based on @yzhao244 , you are the co-committer, right?

**Comment by JunjieChou** [comment]
> @yzhao244 @JunjieChou sure, for admin module, i think it is clear for us. and for schemaregistry moudle, @JunjieChou is working based on @yzhao244 , you are the co-committer, right? 

Yes

**Comment by yzhao244** [comment]
> > @yzhao244 @JunjieChou sure, for admin module, i think it is clear for us. and for schemaregistry moudle, @JunjieChou is working based on @yzhao244 , you are the co-committer, right?
> 
> Yes

Yes, I am going to work with @JunjieChou on Schema Registry for EventMesh together. :)

**Comment by ruanwenjun** [comment]
@yzhao244 @JunjieChou Be careful to make the git commit message clear if your two person submit to one branch, then the community can directly merge to development branch, the all commit log can retain.

Otherwise, community will use squash merge, then the all commit log will be merged into one, this means one person's contribution will lose.

This often happens in other community.

**Comment by JunjieChou** [comment]
@ruanwenjun OK, that's indeed a thing needed to be taken into consideration.

Also, @yzhao244 I have a proposal for our division of work.
As shown in schema registry design doc, there are two stages from client to schema registry service:
1. client <------> eventmesh: eventmesh serves as a middleman, transferring client requests to schema registry.
2. eventmesh <------> schema registry: a separated service handle those requests and send responses.
So each of us could take one stage, then there will not have a conflict on commit log. Which part would you like to take?

If you would like to do the first one, that you just need to modify the persistence layer and combine the codes with admin module. And I will continue the second one.
If you would like to do the second one, you could merge what I have done based on spring boot and continue that. Then I will take the first part based on your previous work. But the commit log may not retain.

You are the first contributor to this series of issues, so you get the option! 🤣

**Comment by qqeasonchen** [comment]
@yzhao244 @JunjieChou hi, admin moucle may neet plugin too, like eventmesh-admin-rocketmq, which used to managen topics or other management functions.

**Comment by yzhao244** [comment]
> @yzhao244 @JunjieChou hi, admin moucle may neet plugin too, like eventmesh-admin-rocketmq, which used to managen topics or other management functions.

@qqeasonchen  @JunjieChou  Yes, you are right. Under eventmesh-admin module, we can manage to create sub modules/plugins such as eventmesh-admin-rocketmq for managing topics and even subGroups. Regarding this PR, it only contains eventmesh-admin module plus readme.

**Comment by yzhao244** [comment]
> @ruanwenjun OK, that's indeed a thing needed to be taken into consideration.
> 
> Also, @yzhao244 I have a proposal for our division of work.
> As shown in schema registry design doc, there are two stages from client to schema registry service:
> 
> 1. client <------> eventmesh: eventmesh serves as a middleman, transferring client requests to schema registry.
> 2. eventmesh <------> schema registry: a separated service handle those requests and send responses.
>    So each of us could take one stage, then there will not have a conflict on commit log. Which part would you like to take?
> 
> If you would like to do the first one, that you just need to modify the persistence layer and combine the codes with admin module. And I will continue the second one.
> If you would like to do the second one, you could merge what I have done based on spring boot and continue that. Then I will take the first part based on your previous work. But the commit log may not retain.
> 
> You are the first contributor to this series of issues, so you get the option! 🤣

@JunjieChou you can go ahead do the schema registry since you are already working on implementing the schema registry by using SpringBoot and sounds you already have coding done lol.. Therefore, please work on the schema registry part.

**Comment by qqeasonchen** [comment]
> > @yzhao244 @JunjieChou hi, admin moucle may neet plugin too, like eventmesh-admin-rocketmq, which used to managen topics or other management functions.
> 
> @qqeasonchen @JunjieChou Yes, you are right. Under eventmesh-admin module, we can manage to create sub modules/plugins such as eventmesh-admin-rocketmq for managing topics and even subGroups. Regarding this PR, it only contains eventmesh-admin module plus readme.

@yzhao244 ok, if there are no more code to be committed to this PR, it can be merged then, and waiting for the plugins.

**Comment by yzhao244** [comment]
> > > @yzhao244 @JunjieChou hi, admin moucle may neet plugin too, like eventmesh-admin-rocketmq, which used to managen topics or other management functions.
> > 
> > 
> > @qqeasonchen @JunjieChou Yes, you are right. Under eventmesh-admin module, we can manage to create sub modules/plugins such as eventmesh-admin-rocketmq for managing topics and even subGroups. Regarding this PR, it only contains eventmesh-admin module plus readme.
> 
> @yzhao244 ok, if there are no more code to be committed to this PR, it can be merged then, and waiting for the plugins.

@qqeasonchen Yes, you are right.. For this PR, there are no more code to be committed. :) .. I will be working on plugins and push via another PR.  thx

**Pull request merged**
