### PR TITLE
[MINOR] Fixed redundant boxing operations

### PR DESCRIPTION
**Pull request by li-xiao-shuang**
Fixes ISSUE#<XXXX>.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Please remove the change of gradle-wrapper.jar, gradle-wrapper.properties, gradlew, gradlew.bat.

**Comment by li-xiao-shuang** [comment]
> Please remove the change of gradle-wrapper.jar, gradle-wrapper.properties, gradlew, gradlew.bat.

can I ignore it in .gitignore file ?

**Comment by ruanwenjun** [comment]
> > Please remove the change of gradle-wrapper.jar, gradle-wrapper.properties, gradlew, gradlew.bat.
> 
> can I ignore it in .gitignore file ?

No, you cannot add this in `.gitignore`. This is lost in master branch by some history reason: )
If you are not in a hurry, you can wait the #680 merged first.

**Comment by li-xiao-shuang** [comment]
> > > Please remove the change of gradle-wrapper.jar, gradle-wrapper.properties, gradlew, gradlew.bat.
> > 
> > 
> > can I ignore it in .gitignore file ?
> 
> No, you cannot add this in `.gitignore`. This is lost in master branch by some history reason: ) If you are not in a hurry, you can wait the #680 merged first.

Do all pr have to wait until they merge together?

**Comment by jonyangx** [comment]
use gralde check  to check code format before checkin.

**Review by jonyangx — APPROVED** [review]

**Pull request merged**
