### PR TITLE
[ISSUE #436] Fix typo errors  for runtime package 

### PR DESCRIPTION
**Pull request by liutaohua**

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@liutaohua Can you fix all the typos in one PR? btw the title should follow the [ISSUE # ] format.

**Comment by ruanwenjun** [comment]
@liutaohua Agree with @qqeasonchen, it may not be a problem in other scenarios, but currently, since many pr may change these file, frequent code change may cause others need to solve the conflict frequently.

**Comment by liutaohua** [comment]
Yes, I agree with you, but first of all, I don't study full-time, so I can only say to combine everything I learn every time.
Second, if you think the typo is irrelevant, I can close the pr and no longer submit the relevant content... 
Thank you

**Comment by qqeasonchen** [comment]
@liutaohua Understood, Thank You for your time, Any contributions are welcomed, but you can submit them one time As comlplete As You can.

**Comment by qqeasonchen** [comment]
@liutaohua I reopened the issue #441 and leave this pr pending so that you can add new commits here.

**Comment by liutaohua** [comment]
> @liutaohua I reopened the issue #436 and leave this pr pending so that you can add new commits here.

thanks Chen

**Comment by liutaohua** [comment]
> @liutaohua I reopened the issue #436 and leave this pr pending so that you can add new commits here.

I think the scope of the title is a bit too large. I'm not a spell checker, so I can't bear having to open every class once and fix all the typo.

I gave a preview of the basic logic of Runtime, and I thought that at least there were no obvious errors in Runtime, and that this PR could be incorporated.

If you think you need me to incorporate all the mistakes I found in the learning process into this PR, please keep it open for a long time. I will resolve the conflicts in an indefinite amount of time, or someone else will remember to fix them during development

**Pull request merged**
