### PR TITLE
[ISSUE #389] Support redis as event store

### PR DESCRIPTION
**Pull request by jjz921024**
#389 

Motivation:  
- Support redis as event store use publish/subscribe

Modifications: 
- Added eventmesh-connector-redis module
- (Todo) unit test

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@jjz921024 Could you please re-submit this feature to branch 1.3.0? since this is a not stable feature, thanks.

**Comment by ruanwenjun** [comment]
@jjz921024 Please rebase from the latest develop branch, the SPI module has been enhanced by #367.
You can get some docs at https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/instructions/eventmesh-runtime-quickstart.md.

**Comment by qqeasonchen** [comment]
@jjz921024 Could you please submmit this feature to branch redis-connector?

**Comment by jjz921024** [comment]
> @jjz921024 Could you please submmit this feature to branch redis-connector?

I have open a another pr #478  for submmit this feature.  In this pr, i seem megre some irrelevant commit due of my mistake, sorry about that.

**Comment by qqeasonchen** [comment]
#478 is duplicate with this, so close it.

**Pull request closed without merging**
