### PR TITLE
[ISSUE #456] Remove license name, add LICENSE file

### PR DESCRIPTION
**Pull request by ruanwenjun**
related issue #456 

1. remove license name in allowed-licenses.txt
2. use LICENSE to announce the license

### CODE REVIEW

**Review by jonyangx — COMMENTED** [review]
========================================================================
LGPL licenses
========================================================================

The following components are provided under the LGPL License. See project link for details.
The text of each license is also included at licenses/LICENSE-[project].txt.

    hibernate-commons-annotations 5.1.2.Final: https://mvnrepository.com/artifact/org.hibernate.common/hibernate-commons-annotations/5.1.2.Final, LGPL 2.1
    hibernate-core 5.4.32.Final: https://mvnrepository.com/artifact/org.hibernate/hibernate-core/5.4.32.Final, LGPL 2.1


refer to:  https://www.apache.org/legal/resolved.html
LICENSE file  must not  include LGPL2.1 license .

**Comment by ruanwenjun** [comment]
@jonyangx Thanks for your reminder, this is a big mistake. I have removed these licenses, since these are not in binary jar. And now the LICENSE only contains binary dependency.

**Comment by ruanwenjun** [comment]
@xwm1992 I think we may still need to use a shell script to check the license, rather than use gradle license check plugin. Because the gradle plugin check result doesn't correct, some of them are not appeared in the binary file.

**Comment by ruanwenjun** [comment]
This pr is ready to review now.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Review by jonyangx — APPROVED** [review]

**Pull request merged**
