### PR TITLE
[Issue #632] clean up maven dependencies

### PR DESCRIPTION
**Pull request by jinrongluo**
[Issue #632] clean up maven dependencies

### CODE REVIEW

**Comment by jinrongluo** [comment]
Hi All, when working on this PR, I found there are a lot of existing files are failing with style checks. I tried my best efforts to fix the check styles of the files I have made the changes. But the changes to one files has the ripple effects of the other java files which has references to my fixes. So there are more files failing with style checks.

I think instead of spending efforts on this PR to fixing the styles. I would recommend open a separate issue and PR to address the checkstyle issues throughout this Eventmesh project as a whole.

This will leave the burdens of fixing the checkstyle errors of future PRs.

**Comment by vongosling** [comment]
@qqeasonchen We could help guys to put forward this optimization.

**Comment by ruanwenjun** [comment]
The ci will only check the file has been modified in the current pr.

**Comment by vongosling** [comment]
I close this pr because of conflicts. We could do more using a new pr, some API and implementation are mixed-used, it could not bring the power of  Gradle ABI compatibility, including some checkstyle problems.

**Pull request closed without merging**
