### PR TITLE
[ISSUE #737] Add Netty license

### PR DESCRIPTION
**Pull request by ruanwenjun**
Fixes ISSUE #737

### Motivation

* Add license files.

### Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not applicable
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@xwm1992 @Shoothzj @pjfanning Take a look? If you are interested.

**Review by Shoothzj — APPROVED** [review]
Sorry for my later reply

**Review by Alonexc — APPROVED** [review]

**Comment by xwm1992** [comment]
I have recognized add a lot sub dependencies of `netty` in project, do we need all these sub dependencies now?
@ruanwenjun @Shoothzj

**Comment by ruanwenjun** [comment]
> I have recognized add a lot sub dependencies of `netty` in project, do we need all these sub dependencies now? @ruanwenjun @Shoothzj

I think there are some binary dependencies we don't need, e.g. `netty-codec-redis`, `netty-codec-dns`, I am not sure, need to be careful when deleting. Currently, we need to add the missing LICENSE file.

**Comment by Shoothzj** [comment]
@ruanwenjun If we don't need, I suggest implement these module separately, I can work on this

**Comment by ruanwenjun** [comment]
> @ruanwenjun If we don't need, I suggest implement these module separately, I can work on this

Great, you can open a new issue to optimize the dependency.

**Review by xwm1992 — APPROVED** [review]

**Pull request merged**
