### PR TITLE
[apache#1151] | [Enhancement] Extraction of constants to runtime module http processor directory

### PR DESCRIPTION
**Pull request by Saranpjs727**
Fixs #1151
Motivation
[Enhancement] Extraction of constants to runtime module http processor directory . 

Documentation
Does this pull request introduce a new feature? (yes / no) No

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@Saranpjs727 It would be better to submit less code per PR, you can submit several PRs for this.

**Comment by qqeasonchen** [comment]
@Saranpjs727 and each PR links to a new issue that you might need to create

**Comment by Saranpjs727** [comment]
> @Saranpjs727 and each PR links to a new issue that you might need to create

sure @qqeasonchen will do that

**Comment by qqeasonchen** [comment]
@Saranpjs727 do you need any help?

**Comment by Saranpjs727** [comment]
@qqeasonchen removed some codes that are not covered under this issue. Can u check and give comments.

**Review by qqeasonchen — APPROVED** [review]
LGTM,Maybe you can submit less code each PR, so that you have more PRs and easy for community to review.

**Pull request merged**
