### PR TITLE
[ISSUE-837]Add NOTICE

### PR DESCRIPTION
**Pull request by ruanwenjun**
Fixes ISSUE #837

### Modifications

* Add NOTICE file
* Add registry plugin into distribution

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by xwm1992 — APPROVED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@ruanwenjun It would be better to split into several small prs.

**Comment by ruanwenjun** [comment]
> @ruanwenjun It would be better to split into several small prs.

Done

**Comment by ruanwenjun** [comment]
I didn't change `eventmesh-protocol-plugin/eventmesh-protocol-http/out/production/resources/META-INF/eventmesh/org.apache.eventmesh.protocol.api.ProtocolAdaptor` this is a BUG?

**Review by xwm1992 — APPROVED** [review]
LGTM

**Pull request merged**
