### PR TITLE
[ISSUE #310] Enable Github Actions for license check and fix license headers

### PR DESCRIPTION
**Pull request by SteveYurongSu**
For more details, see the discussion in #310.
Thanks to @liangyuanpeng for the previous work on PR #313 :D

### CODE REVIEW

**Comment by SteveYurongSu** [comment]
Hi @qqeasonchen @kezhenxu94 , please take a look at this PR, thanks. ❤️

**Comment by kezhenxu94** [comment]
> Hi @qqeasonchen @kezhenxu94 , please take a look at this PR, thanks. ❤️

It looks good to me, thanks for setting it up

**Comment by qqeasonchen** [comment]
@SteveYurongSu @kezhenxu94 @liangyuanpeng thanks for all your work.

**Comment by qqeasonchen** [comment]
@SteveYurongSu It seems still use skywalking-eyes to check, and what is the differencies with  #313 ?

**Comment by kezhenxu94** [comment]
> @SteveYurongSu It seems still use skywalking-eyes to check, and what is the differencies with #313 ?

I think because there is no update in #313?

**Comment by SteveYurongSu** [comment]
> > @SteveYurongSu It seems still use skywalking-eyes to check, and what is the differencies with #313 ?
> 
> I think because there is no update in #313?

Yep... 

Of course, there are other minor differences,:
1. This PR uses a fixed version (instead of the `@main` version) of skywalking-eyes to check. This can avoid the influence of different versions of skywalking-eyes and ensure the stability of the pipeline.
2. Missing Apache headers are all added in my PR.
3. The "Build status" badge is updated.

**Comment by qqeasonchen** [comment]
This branch has conflicts that must be resolved.

**Comment by SteveYurongSu** [comment]
> This branch has conflicts that must be resolved.

Resolved.

**Pull request merged**
