### PR TITLE
Extraction of constants grpc、JAVA and application/cloudevents+json.

### LINKED ISSUE #1081: [Enhancement] Extraction of constants [EventMeshClientUtil CloudEventProducer]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image

### Describe the solution you'd like

Located at:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client
Extract the constants in the image, define them with "static final" and put them in this class.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by RiemannChow**
Fixes #1081.

### Motivation

Extraction of constants grpc、JAVA and application/cloudevents+json are in the project.

### Modifications

The classes involved are Constant,EventMeshClientUtil,GrpcMessageProtocolResolver,and others.

### Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@RiemannChow please check your email in your GitHub config with your commit email, whether they are the same, it seems your contribution does not count in.

**Comment by RiemannChow** [comment]
> @RiemannChow please check your email in your GitHub config with your commit email, whether they are the same, it seems your contribution does not count in.

It doesn't matter, I have changed the email, continue to contribute next time.

**Comment by qqeasonchen** [comment]
> > @RiemannChow please check your email in your GitHub config with your commit email, whether they are the same, it seems your contribution does not count in.
> 
> 
> 
> It doesn't matter, I have changed the email, continue to contribute next time.

@RiemannChow Your committes have been reverted, please recommotte again.

**Pull request merged**
