### PR TITLE
[ISSUE #982] Explicit usage of byte encoding

### LINKED ISSUE #982: [Bug] Reliance on default encoding
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

This bug happens in many packages.

### How to reproduce

It may happen if the program runs on other platforms.

### Debug logs

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by HeZean**
Fixes #982.

### Modifications

Explicitly set the encoding charset for string-char or char-string conversions.

### Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@HeZean Great job, could you please make this into several small pr?

**Comment by HeZean** [comment]
> @HeZean Great job, could you please make this into several small pr?

With pleasure, does that mean submitting one PR for each module? Could you please further point it out

**Comment by qqeasonchen** [comment]
> > @HeZean Great job, could you please make this into several small pr?
> 
> With pleasure, does that mean submitting one PR for each module or so? Could you please further point it out

yes, that would be better to review, thx.

**Comment by HeZean** [comment]
Hi @qqeasonchen, I just remembered that most changes are related to `Constants.DEFAULT_CHARSET`, which was changed from string "UTF-8" to charset `StandardCharset.UTF_8`, splitting this PR may be not that feasible since it would break some code (e.g. some code was `Charset.forName(Constants.DEFAULT_CHARSET)` should be changed to `Constants.DEFAULT_CHARSET`)

**Comment by HeZean** [comment]
Maybe could you just review the changes thoroughly? they are all trivial modifications.

**Comment by qqeasonchen** [comment]
> Maybe could you just review the changes thoroughly? they are all trivial modifications.

Got it, but smaller prs would be easy to review if you wish, thx.

**Review by qqeasonchen — DISMISSED** [review]

**Comment by qqeasonchen** [comment]
@HeZean please take care of the CI check fails

**Comment by HeZean** [comment]
okay, i'll fix it soon in a commit

**Review by HeZean — COMMENTED** [review]
Hi @qqeasonchen PTAL, sorry that the amount of related files was kind of.. too much, but I think it won't cost too much time to review it

**Comment by HeZean** [comment]
The license checker failed, I've opened #1188 and will fix it in another pr.

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Pull request merged**
