### PR TITLE
remove openschema implementation from em project

### PR DESCRIPTION
**Pull request by yzhao244**
Fixes ISSUE #614 

### Motivation

 remove openschema implementation out of eventmesh project. 

### Modifications

 remove all open schema implementation code out of eventmesh project. Add openschema dependency to em and suggest eventmesh project to create a client to communicate with openschema registry. 

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by yzhao244** [comment]
@qqeasonchen @ruanwenjun @JunjieChou

**Review by vongosling — APPROVED** [review]

**Comment by qqeasonchen** [comment]
Eventmesh only needs to depends on some common code, since SchemaRegistry runs as a service outof EventMesh i think.

**Comment by vongosling** [comment]
Plx resolve the conflicts

**Comment by yzhao244** [comment]
> Plx resolve the conflicts

conflicts resolved

**Pull request merged**
