### PR TITLE
fixes #3260

### LINKED ISSUE #3260: [Enhancement] Method invocation 'getBytes' may produce 'NullPointerException'[EventMeshTestUtils]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java line 180,195

### Describe the solution you'd like

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nikam14**
method invocation getbytes null pointer error fixed.

### CODE REVIEW

**Comment by weihubeats** [comment]
Please refer to other pr to modify the pr title and associate relevant issues

**Review by weihubeats — COMMENTED** [review]
Please refer to other pr to modify the pr title and associate relevant issues

**Review by mxsm — COMMENTED** [review]
@nikam14  Please fix code style, the CI not pass

**Comment by Alonexc** [comment]
image
Import order is wrong.
image

**Pull request closed without merging**
