### PR TITLE
[Issues #405]code polish and fix typo

### PR DESCRIPTION
**Pull request by tydhot**
#TBD

### CODE REVIEW

**Comment by xwm1992** [comment]
hi, @tydhot welcome and thank you for your contribution, you can associate this pull request to the issue below, it's convenient to manage this type of pull requests, thanks.
https://github.com/apache/incubator-eventmesh/issues/405

**Comment by tydhot** [comment]
@xwm1992 thanks 4 your advice. :)

**Comment by tydhot** [comment]
@xwm1992 btw, I found the greeting check failed. Do you know the reason?

**Comment by qqeasonchen** [comment]
@tydhot welcome

**Comment by SteveYurongSu** [comment]
Hi @tydhot, please pull and merge the lastest code then check whether the workflows run :D

**Comment by tydhot** [comment]
@SteveYurongSu it is work now :)

**Review by xwm1992 — APPROVED** [review]
Good job

**Pull request merged**
