### PR TITLE
[ISSUE #442] Fix findings filtered by Checkstyle workflow

### PR DESCRIPTION
**Pull request by SteveYurongSu**
Fixes ISSUE #442.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

I introduced CheckStyle workflow in PR #438, but did not fix the issues that Checkstyle found.

### Modifications

*Describe the modifications you've done.*

* Fixed all findings filtered by the Checkstyle workflow.

* Modified Checkstyle config file:
```xml
<module name="RegexpSingleline">
    <property name="format" value="System\..+\.println"/>
    <property name="message" value="Prohibit invoking System.*.println in source code !"/>
</module>
```

### CODE REVIEW

**Comment by ruanwenjun** [comment]
I also do the same thing at #433, if this pr is merged first, I will rebase.

**Comment by qqeasonchen** [comment]
It seems this pr needs be merged first or every other new pr will be checked failed.

**Comment by ruanwenjun** [comment]
@qqeasonchen Yes, If there are no other problems, this pr can be merged first, otherwise  the other commits will be blocked.

**Comment by qqeasonchen** [comment]
Have any other guys reviewed already?

**Review by ruanwenjun — APPROVED** [review]
LGTM, When I submitted a pr, I found that the file `sChat2.jks` seems to break the rules in checkStyle, do we need to exclude this file? I am not sure whether this will happen.

**Comment by SteveYurongSu** [comment]
> LGTM, When I submitted a pr, I found that the file `sChat2.jks` seems to break the rules in checkStyle, do we need to exclude this file? I am not sure whether this will happen.

@ruanwenjun Thanks for reviewing! 

I have the same question. It seems that `sChat2.jks` is an unexpected binary file, should we remove the file? @qqeasonchen

**Comment by ruanwenjun** [comment]
> > LGTM, When I submitted a pr, I found that the file `sChat2.jks` seems to break the rules in checkStyle, do we need to exclude this file? I am not sure whether this will happen.
> 
> @ruanwenjun Thanks for reviewing!
> 
> I have the same question. It seems that `sChat2.jks` is an unexpected binary file, should we remove the file? @qqeasonchen

If this file is not needed, we can remove it, and if this is needed then we can filter it like below:
```java
<module name="BeforeExecutionExclusionFileFilter">
    <property name="fileNamePattern" value="./eventmesh-runtime/conf/sChat2.jks$"/>
  </module>
``` 
Or using [checkStyle-suppressions.xml](https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml)

**Comment by qqeasonchen** [comment]
sChat2.jks can be removed.

**Pull request merged**
