### PR TITLE
[ISSUE #274] Adding Eventmesh Stream component to support Event Streaming 

### PR DESCRIPTION
**Pull request by msdhinesh-geek**
This PR consist of introduction and architecture information related to new feature EventMesh-Cloud-Stream, later commit will add detailed design, component functionality, why Camel instead of Spring Integration.

### CODE REVIEW

**Comment by msdhinesh-geek** [comment]
@qqeasonchen help me to resolve this.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek how about eventmesh-stream instead of eventmesh-cloud-stream？

**Comment by msdhinesh-geek** [comment]
@qqeasonchen eventmesh-stream is good, Will use this PR.

**Comment by qqeasonchen** [comment]
> @qqeasonchen eventmesh-stream is good, Will use this PR.

Other file names need to be updated too, also please solve the check failed actions.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek looking forward to your detail design doc :)

**Comment by msdhinesh-geek** [comment]
@qqeasonchen  I have update eventmesh-stream-design.md doc with detailed functionality including design and interfaces for component producer and consumer. Its just an abstract view of functionality. 
@qqeasonchen  let me know if you want to discuss design or want to add any specific information in doc.

**Comment by vongosling** [comment]
This is a very interesting topic about EventMesh. @qqeasonchen  could we create a branch for this feature discussion, we could merge and review it as an ASF cooperation model.

**Comment by qqeasonchen** [comment]
> This is a very interesting topic about EventMesh. @qqeasonchen could we create a branch for this feature discussion, we could merge and review it as an ASF cooperation model.

sure ok.

**Comment by qqeasonchen** [comment]
> @qqeasonchen I have update eventmesh-stream-design.md doc with detailed functionality including design and interfaces for component producer and consumer. Its just an abstract view of functionality.
> @qqeasonchen let me know if you want to discuss design or want to add any specific information in doc.

@msdhinesh-geek Thanks, this design doc can be merge to develop first and i will create a new feature branch to continue discuss and develop on it.

**Pull request merged**
