### PR TITLE
 [ISSUE #1202] Remove warning code

### LINKED ISSUE #1202: [Enhancement] gradle compile warning
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

gradle compile warning

### Describe the solution you'd like

modify code

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by BigXin0109**
Fixes #1202 
### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

Remove warning code

### Modifications

*Describe the modifications you've done.*

Remove warning code

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@BigXin0109 please add a issue for this.

**Comment by BigXin0109** [comment]
> @BigXin0109 please add an issue for this.

ok

**Comment by BigXin0109** [comment]
> @BigXin0109 please add an issue for this.

ok

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Pull request merged**
