### PR TITLE
[Issue #553] Adding design doc for EventMesh Workflow

### PR DESCRIPTION
**Pull request by jinrongluo**
related ISSUE #553

### Motivation

Adding design doc for EventMesh Workflow.

### Modifications

Adding design doc for EventMesh Workflow.

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@jinrongluo Good design, in your design, we need to create a workflow engine module, and the engine use `eventmesh-sdk` to manage the event, use `serverlessworkflow` DSL to  organize the event. So the engine should deploy as another process?

**Comment by jinrongluo** [comment]
> @jinrongluo Good design, in your design, we need to create a workflow engine module, and the engine use `eventmesh-sdk` to manage the event, use `serverlessworkflow` DSL to organize the event. So the engine should deploy as another process?

Yes. The engine should run in a separate process from EventMesh Runtime.  We can use SpringBoot to build the engine.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by qqeasonchen** [comment]
LGTM，I think can merge it first, and launch a disscuss email to dev@eventmesh.apache.org, to see if anyone can involve.

**Pull request merged**
