### PR TITLE
[ISSUE #1526] update all map fetch value

### LINKED ISSUE #1526: [Enhancement] Method check a map with containsKey(), before using get() [SimpleMessage]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at: org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java line 499 and 1643
This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row.

### Describe the solution you'd like

 It is much simpler to just fetch the value with get, and checking for non null instead.
eg:
                Map  myMap = getSomeMap();
     	    	String value = myMap.get("foo");
    	    	if (value != null) {
    	    		....
    	    	}

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by venu-prasanna**
Made changes for fetching value using the key from the map as per suggestion in #1526 

Fixes #1526 

### Documentation

- Does this pull request introduces a new feature? no
- If yes, how is the feature documented? not applicable
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by xwm1992 — APPROVED** [review]
LGTM

**Comment by xwm1992** [comment]
please solve the conflict @venu-prasanna

**Comment by horoc** [comment]
hi，@venu-prasanna , may I know why this pr modify GRCP proto generate file?

**Comment by fengyongshe** [comment]
@xwm1992  SimpleMessage in grpc proto is in wrong status after generated .
> Task :eventmesh-common:compileJava FAILED
FAILURE: Build failed with an exception.

```
/Users/fys/project/test/incubator-eventmesh/eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java:81: 错误: 程序包RFequestHeader不存在
                        RFequestHeader.Builder subBuilder = null;
                                      ^
```

This's should be a wrong merge.  This is no R**F**equestHeader ( Should be RequestHandler )  .

**Pull request merged**
