### PR TITLE
[ISSUE #2048] Update actions to update your dependencies

### LINKED ISSUE #2048: [Enhancement] Update deprecated node version in github workflow actions
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases). Github actions have started using node 16 and the usage of old version in the workflow config is leading to the following warning:
To see the warnings

1. Go to Actions tab in Github
2. Select any succeeded workflow run in "Continous Integration" workflow
3. You will see warnings below the workflow run details.
Screenshot 2022-10-31 at 6 30 23 PM

### Describe the solution you'd like

We need to upgrade the version of node in the workflow config [file](https://github.com/apache/incubator-eventmesh/blob/master/.github/workflows/ci.yml) for the actions that shows warning. Follow this page for [reference](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by joaovitoras**
Fixes #2048 

### Motivation

To update node dependencies is necessary update action versions

### Modifications

* Update actions/checkout from v2 to v3
* Update github/codeql-action/init from v1 to v2
* Update actions/setup-java from v1 to v3
* Fix issue template typo

### Documentation

- Does this pull request introduce a new feature? (yes / no)
  - no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - not applicable 
- If a feature is not applicable for documentation, explain why?
  - Is a update to ci
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by joaovitoras** [comment]
Master CI is broken, so I this PR is broken to

**Comment by xwm1992** [comment]
@joaovitoras thanks guys, you can submit this pr to the master branch.

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Comment by qqeasonchen** [comment]
@joaovitoras you need to merge to master.

**Review by qqeasonchen — CHANGES_REQUESTED** [review]
request to master

**Comment by joaovitoras** [comment]
Base changed

**Review by qqeasonchen — APPROVED** [review]

**Pull request merged**
