### PR TITLE
[ISSUE #438] Enable Github Actions for Checkstyle

### PR DESCRIPTION
**Pull request by SteveYurongSu**
Fixes ISSUE #438.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

I noticed that there are folks working on issue #428 (#431), translating or removing Chinese chars in code.
Manually checking for this kind of code style can be a pain.
But, we can make the process of code style check automated with less pain by introducing Checkstyle into CI.

### Modifications

*Describe the modifications you've done.*

1. add a config file for checkstyle
2. introduce the checkstyle job into CI workflow
3. remove a useless file: style/copyright/Apache.xml 

image

### CODE REVIEW

**Comment by ruanwenjun** [comment]
We can also use the checkstyle plugin in IDEA to help us check our code style.
Does the checkstyle file need to be consistent with the codestyle file? It seems that we don't have a clear code specification currently.

**Comment by SteveYurongSu** [comment]
@ruanwenjun Thanks for your comments!

> We can also use the checkstyle plugin in IDEA to help us check our code style.

Sure! This can make our codebase healthy and clean!

> Does the checkstyle file need to be consistent with the codestyle file?

I only added the following checks in the Checkstyle configuration file:

* invoking System.out.println in source code
* @author copyright
* Chinese characters
* PackageName must match "^(org)\.apache(\.[a-zA-Z][a-zA-Z0-9]*)+$"

>  It seems that we don't have a clear code specification currently.

When we have a clear code style, we can add more constraints. 
Personally, I prefer the Google coding style. 😊

**Comment by ruanwenjun** [comment]
@SteveYurongSu Great

**Comment by qqeasonchen** [comment]
@SteveYurongSu Will it become easier failed each build?

**Comment by SteveYurongSu** [comment]
> @SteveYurongSu Will it become easier failed each build?

I only added the following checks in the Checkstyle configuration file:

* invoking System.out.println in source code
* @author copyright
* Chinese characters
* PackageName must match "^(org).apache(.[a-zA-Z][a-zA-Z0-9]*)+$"

If a checkstyle workflow fails, there must be a finding related to one of the above cases, which means the author must modify the code. 😆

**Comment by qqeasonchen** [comment]
LGTM

**Pull request merged**
