### PR TITLE
[ISSUE #958] Update licenses files, add licenses of go sdk.

### PR DESCRIPTION
**Pull request by xwm1992**
Fixes ISSUE #958 .

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@xwm1992 It seems you have deleted the license directory and submit nothing?

**Comment by ruanwenjun** [comment]
Need to add announce in NOTICE an LICENSE file.

**Comment by xwm1992** [comment]
> Need to add announce in NOTICE and LICENSE file.

Done.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
