### PR TITLE
[Enhancement] eventmesh server go standalone connector

### PR DESCRIPTION
**Pull request by horoc**
### Motivation

#1124 

### Modifications

add a standalone connector in go server

### CODE REVIEW

**Comment by walleliu1016** [comment]
Is you PR run corretlly? I also written the standalone connector. If you PR ok. I will drop my code, and merge you PR。

**Comment by walleliu1016** [comment]
@horoc

**Comment by horoc** [comment]
> Is you PR run corretlly? I also written the standalone connector. If you PR ok. I will drop my code, and merge you PR。

Oh, sorry for the duplication.
According to the result I have tested so far, It seems good to me.  Maybe you can help to review this implementation to check if it's acceptable. lots of thanks.

**Comment by walleliu1016** [comment]
> > Is you PR run corretlly? I also written the standalone connector. If you PR ok. I will drop my code, and merge you PR。
> 
> 
> 
> Oh, sorry for the duplication.
> 
> According to the result I have tested so far, It seems good to me.  Maybe you can help to review this implementation to check if it's acceptable. lots of thanks.
> 
> 

OK，it is my problem. I forgot to read issue. I will merge the code after CR, thank you pr。

**Comment by walleliu1016** [comment]
> > Is you PR run corretlly? I also written the standalone connector. If you PR ok. I will drop my code, and merge you PR。
> 
> 
> 
> Oh, sorry for the duplication.
> 
> According to the result I have tested so far, It seems good to me.  Maybe you can help to review this implementation to check if it's acceptable. lots of thanks.
> 
> 

Hi @horoc 
please contact the eventmesh assistant and join the WeChat go sig group。

**Comment by horoc** [comment]
> > > Is you PR run corretlly? I also written the standalone connector. If you PR ok. I will drop my code, and merge you PR。
> > 
> > 
> > Oh, sorry for the duplication.
> > According to the result I have tested so far, It seems good to me.  Maybe you can help to review this implementation to check if it's acceptable. lots of thanks.
> 
> Hi @horoc please contact the eventmesh assistant and join the WeChat go sig group。

Ok, have already applied, and look forward to joining.

**Pull request merged**
