### PR TITLE
[ISSUE #580] Add checkstyle gradle plugin

### LINKED ISSUE #580: [Enhancement] Add checkstyle gradle plugin
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add checkstyle gradle plugin, then contributor cannot rely on IDE plugin

### Describe the solution you'd like

Add checkstyle gradle plugin

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ruanwenjun**
The check style will not be trigger in build, you need to manually execute `./gradlew check`.

And this pr also change the plugin package code, when add a new plugin, need to add a gradle.properties file, and defined the plugin name.
close #580

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@qqeasonchen @xwm1992 This pr is ready for review, please take a look.

**Comment by ruanwenjun** [comment]
Here are some error caused by check code style in build, I will take a look tonight.

**Comment by qqeasonchen** [comment]
LGTM

**Comment by ruanwenjun** [comment]
@xwm1992 Now it's ready for review.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Pull request merged**
