### PR TITLE
[Doc] Update the eventmesh keywords.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
Fixes [#<1520>.](https://github.com/apache/incubator-eventmesh/issues/1520).

### Motivation

- Update the _eventmesh_ keywords.

### Modifications

- Update the _eventmesh_ keywords.

### Documentation

- Does this pull request introduce a new feature? (**no**)
- If yes, how is the feature documented? (**not applicable**)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@qqeasonchen ,Sorry to bother you, can you help me review this pr?Thank you.

**Comment by xwm1992** [comment]
please check the email of the committs is your github account email not your company email or others.

**Comment by xwm1992** [comment]
I saw you have contributed for [#1499](https://github.com/apache/incubator-eventmesh/pull/1499), but this wasn't counted as contributor, maybe your email of the commits wasn't correct.

**Comment by liuzhuang2017** [comment]
@xwm1992 , Thank you for your reply, I checked the commit, my github email is "justdodt@outlook.com" and found no errors.

image

**Review by xwm1992 — APPROVED** [review]
LGTM

**Pull request merged**
