### PR TITLE
Update 01-workflow.md

### PR DESCRIPTION
**Pull request by hanshal101**
Please tell if anything should be changed

### CODE REVIEW

**Comment by xwm1992** [comment]
@hanshal101 this pr translate the en doc, please don't put this doc under the en file directory.

**Comment by hanshal101** [comment]
@xwm1992 so should I make a new directory. And if yes so what should I name it?

**Comment by hanshal101** [comment]
@Alonexc should I make changes in zh directory ?

**Review by qqeasonchen — APPROVED** [review]

**Comment by xwm1992** [comment]
@hanshal101 yes, the chinese document under the zh directory.

**Comment by hanshal101** [comment]
@xwm1992 GOTCHA

**Comment by hanshal101** [comment]
@xwm1992 The changes has already been made in the zh directory

**Pull request merged**
