### PR TITLE
[Docs] Add http request doc instruction

### LINKED ISSUE #925: [Doc] Add http request doc instruction
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Since we support the http request via curl command we need add the http request instruction docs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xwm1992**
Add http request doc instruction for using curl command.
close #925

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@xwm1992 I suggest you create an issue with it, and use curl instead of the postman in the doc.

**Review by ruanwenjun — DISMISSED** [review]
LGTM. 
NIT: Can we provide the postman template for example.

**Comment by xwm1992** [comment]
> @xwm1992 I suggest you create an issue with it, and use curl instead of the postman in the doc.

done

**Review by qqeasonchen — APPROVED** [review]
LGTM

**Pull request merged**
