### PR TITLE
Update 11-prometheus.md

### PR DESCRIPTION
**Pull request by hanshal101**

### CODE REVIEW

**Comment by xwm1992** [comment]
@hanshal101 please solve the conflicts.

**Comment by hanshal101** [comment]
@xwm1992 can you please guide me how to resolve conflicts as i am new to open source

**Comment by xwm1992** [comment]
> @xwm1992 can you please guide me how to resolve conflicts as i am new to open source

you can ask wechat helper for help.

**Comment by hanshal101** [comment]
@xwm1992 can you please guide me how to ask wechat for help

**Comment by xwm1992** [comment]
> @xwm1992 can you please guide me how to ask wechat for help

follow this link https://eventmesh.apache.org/community/contact

**Comment by xwm1992** [comment]
I'll close this pr since nothing has been changed for a long time. @hanshal101

**Pull request closed without merging**
