### PR TITLE
[ISSUE #1286] add go server RocketMQ producer

### PR DESCRIPTION
**Pull request by horoc**
### Motivation

#1286 

### Modifications

add go server RocketMQ producer

### Documentation

None

### CODE REVIEW

**Comment by walleliu1016** [comment]
LGTM

**Comment by walleliu1016** [comment]
please resolve the conflict first.

**Comment by walleliu1016** [comment]
please add the license check

**Comment by horoc** [comment]
seems the producer has merged in another pr, close it first.

**Pull request closed without merging**
