### PR TITLE
[Issue #417] gRPC design doc and protobuf models

### PR DESCRIPTION
**Pull request by jinrongluo**
Fixes ISSUE #417.

### Motivation

 - use gRPC protocol to support polyglot eventmesh client SDK

### Modifications

 - gRPC protocol design doc
- gRPC protobuf model
- gRPC protobuf code generation

### Documentation

- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? yes

### CODE REVIEW

**Comment by vongosling** [comment]
You could refer here to exclude the grpc auto-created file from the general check from ck. https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_tasks

**Comment by vongosling** [comment]
What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Execution failed for task ':checkLicense'.
Use '--warning-mode all' to show the individual deprecation warnings.

@qqeasonchen I think we have some improvement when resorting to GitHub's building checks.

**Comment by qqeasonchen** [comment]
@jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.

**Comment by qqeasonchen** [comment]
> What went wrong: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0. Execution failed for task ':checkLicense'. Use '--warning-mode all' to show the individual deprecation warnings.
> 
> @qqeasonchen I think we have some improvement when resorting to GitHub's building checks.

@keranbingaa can you help to fix it?

**Comment by vongosling** [comment]
> > What went wrong: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0. Execution failed for task ':checkLicense'. Use '--warning-mode all' to show the individual deprecation warnings.
> > @qqeasonchen I think we have some improvement when resorting to GitHub's building checks.
> 
> @keranbingaa can you help to fix it?

https://docs.gradle.org/7.3/userguide/compatibility.html

**Comment by keranbingaa** [comment]
@vongosling @qqeasonchen ok，I will try to fix it

**Comment by vongosling** [comment]
@jinrongluo We could move code to grpc branch temporarily, review after merge  @qqeasonchen

**Comment by keranbingaa** [comment]
> image this is the reason for CI/CD check failed, please excute `gradlew checkLicense` task, check the licenses in the `..\incubator-eventmesh\build\reports\dependency-license\dependencies-without-allowed-license.json` file, if theses licenses are allowed, please copy these texts into `..\tool\license\allowed-licenses.txt`

@jinrongluo maybe you need do this to solve the failed check

**Comment by jinrongluo** [comment]
> > image this is the reason for CI/CD check failed, please excute `gradlew checkLicense` task, check the licenses in the `..\incubator-eventmesh\build\reports\dependency-license\dependencies-without-allowed-license.json` file, if theses licenses are allowed, please copy these texts into `..\tool\license\allowed-licenses.txt`
> 
> @jinrongluo maybe you need do this to solve the failed check

Thanks @keranbingaa  I adding the allowed licenses for grpc and protobuf. 

the commit is here - https://github.com/apache/incubator-eventmesh/pull/594/commits/0ef7783ff11fb01671c0e540db50df0cc1e2ba19

**Comment by jinrongluo** [comment]
> > image this is the reason for CI/CD check failed, please excute `gradlew checkLicense` task, check the licenses in the `..\incubator-eventmesh\build\reports\dependency-license\dependencies-without-allowed-license.json` file, if theses licenses are allowed, please copy these texts into `..\tool\license\allowed-licenses.txt`
> 
> @jinrongluo maybe you need do this to solve the failed check

Thanks @keranbingaa  I adding the allowed licenses for grpc and protobuf. 

the commit is here - https://github.com/apache/incubator-eventmesh/pull/594/commits/0ef7783ff11fb01671c0e540db50df0cc1e2ba19

**Comment by qqeasonchen** [comment]
> @jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.

@jinrongluo we may discuss this first before merge.

**Comment by qqeasonchen** [comment]
> > @jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.
> 
> @jinrongluo we may discuss this first before merge.

Glad to see the sdk-gprc implementation, runtime implementation will commit later, right?

**Comment by jinrongluo** [comment]
> > > @jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.
> > 
> > 
> > @jinrongluo we may discuss this first before merge.
> 
> Glad to see the sdk-gprc implementation, runtime implementation will commit later, right?

Yes, @qqeasonchen this PR is about protobuff message design. the actual implementation will be coming in next PR. Thanks.

**Comment by jinrongluo** [comment]
> > @jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.
> 
> @jinrongluo we may discuss this first before merge.

I agree. in the actual grpc implementation, I will use plugins. This PR is only about design.

**Comment by qqeasonchen** [comment]
> > > @jinrongluo if grpc implementation is a plugin, there may need a api for grpc/http/tcp etc.
> > 
> > 
> > @jinrongluo we may discuss this first before merge.
> 
> I agree. in the actual grpc implementation, I will use plugins. This PR is only about design.

ok, then it can be merged first.

**Comment by vongosling** [comment]
It's important to note that this is quite a difficult refactoring. you could refer quarkus codes. https://quarkus.io/guides/grpc-getting-started.

I'd like to help to opt code for this feature, looking forwards to your code :-)

**Pull request merged**
