### PR TITLE
[ISSUE #3169] Replace `print` with `logger`

### LINKED ISSUE #3169: [Enhancement] 'System.out' printout is not allowed in test classes.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
located at:
eventmesh-common/src/test/java/org/apache/eventmesh/common/loadbalance/WeightRandomLoadBalanceSelectorTest.java line 55,37

### Describe the solution you'd like

use logger:
image
add final:
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Bannirui**
Fixes #3169 .

### Modifications

To optimize `Code-Style`, locating at `org.apache.eventmesh.common.loadbalance.WeightRandomLoadBalanceSelectorTest`

- [X] Line 37: add `final` modifier
- [X] Line 49, 50, 72, 73: optimize spaces
- [X] Line 55: using `logger` ranter than `System.out.println`

### Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
Hi @Bannirui how a about use lombok @Sl4j annocation

**Comment by Bannirui** [comment]
@mxsm Done. However, in my opinion, use no lombok plugin if possible...

**Comment by mxsm** [comment]
> @mxsm Done. However, in my opinion, use no lombok plugin if possible...

@Bannirui  The Lombok framework is widely used in the project, and it is also part of the project's specifications. Therefore, I believe in adhering to the project's specifications. If there is a need to cancel the use of the Lombok framework, I suggest discussing it within the community to determine if it is necessary to do so.

**Comment by Bannirui** [comment]
> > @mxsm Done. However, in my opinion, use no lombok plugin if possible...
> 
> @Bannirui The Lombok framework is widely used in the project, and it is also part of the project's specifications. Therefore, I believe in adhering to the project's specifications. If there is a need to cancel the use of the Lombok framework, I suggest discussing it within the community to determine if it is necessary to do so.

uh uh, it's just my view.

**Review by jonyangx — APPROVED** [review]

**Pull request merged**
