### PR TITLE
[WIP][ISSUE #199] Support Kafka connector plugin and Kafka as event store #199

### LINKED ISSUE #199: Support Kafka connector plugin and Kafka as event store
Support Kafka connector to deliver event to Kafka, and please help me how can i implement this feature.

### PR DESCRIPTION
**Pull request by ruanwenjun**
close #199

### CODE REVIEW

**Comment by qqeasonchen** [comment]
@ruanwenjun good job!

**Comment by xwm1992** [comment]
hi, @ruanwenjun I try to use pub/sub message with kafka connector, but I can't use this kafka plugin. Here are some problem below.
1.This pr code version behind latest code version, try to pull the latest code may be better. such as some packages name still contains webank in eventmesh-common module and eventmesh-api module.
 2.when I try to use kafka plugin to pub/sub messages, the problem is:
image
jdk spi can't load this plugin, please help take a look, I'll continue to follow up related questions.

**Comment by xwm1992** [comment]
**OMSConsumerAdaptor** and **OMSProducerAdaptor** these two adaptors implementations need constructor without parameters for jdk spi requirements, moving the constructors configuration to **init method** may be better. Except for the problem above, here also have problem below, please take a look ,thanks @ruanwenjun .
image

**Comment by ruanwenjun** [comment]
> hi, @ruanwenjun I try to use pub/sub message with kafka connector, but I can't use this kafka plugin. Here are some problem below.
> 1.This pr code version behind latest code version, try to pull the latest code may be better. such as some packages name still contains webank in eventmesh-common module and eventmesh-api module.
> 2.when I try to use kafka plugin to pub/sub messages, the problem is:
> image
> jdk spi can't load this plugin, please help take a look, I'll continue to follow up related questions.

@xwm1992 Hi, I have a question. Currently, the branch 1.3.0 is behind the development very much, can I checkout directly from develop branch and push to 1.3.0?

**Comment by xwm1992** [comment]
> @xwm1992 Hi, I have a question. Currently, the branch 1.3.0 is behind the development very much, can I checkout directly from develop branch and push to 1.3.0? Thanks.

It's ok, you are welcome to do so. You can also update your branch code version first, because we try to do the full test under this branch you submit.

**Comment by ruanwenjun** [comment]
@xwm1992 Please help me test again, thanks a lot.

**Comment by Jackzeng1224** [comment]
@ruanwenjun   hello，I can’t send and receive messages normally with the Kafka module. It seems that the production of messages cannot be monitored. Can you see that messages are sent and received normally when you start project monitoring?

**Comment by ruanwenjun** [comment]
@Jackzeng1224 Yes, I can see the log that the message has been sent to kafka.
You can use `AsyncSyncRequestInstance` to send async requests, and I find a bug in `LiteProducer` line 218.
https://github.com/apache/incubator-eventmesh/blob/737c0f09efeba61a62653d33fd553491af7d0deb/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/LiteProducer.java#L207-L219

This method should be async, but it sends a sync command, I will fix in another pr.
And you can modified the line 218 to 
```java
requestParam.addHeader(ProtocolKey.REQUEST_CODE, String.valueOf(RequestCode.MSG_SEND_ASYNC.getRequestCode()))
```
Then you will see below log in runtime module:
```
2021-07-27 19:28:37,824 INFO  [kafka-producer-network-thread | producer-1] message(SendAsyncMessageProcessor.java:196) - message|eventMesh2mq|REQ|ASYNC|send2MQCost=4ms|topic=TEST-TOPIC-TCP-ASYNC|bizSeqNo=920594188447336930612967879404|uniqueId=243186356065686374194669481534
```
But the response in `AsyncSyncRequestInstance` is also failed, I think it might be another issue.
```java
2021-07-27 19:48:40,956 DEBUG [main] AsyncSyncRequestInstance(AsyncSyncRequestInstance.java:81) - sendmsg failed
org.apache.eventmesh.common.EventMeshException: com.alibaba.fastjson.JSONException: syntax error,except start with { or [,but actually start with error
	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:94) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:41) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.eventmesh.client.http.http.HttpUtil.post(HttpUtil.java:149) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.apache.eventmesh.client.http.producer.LiteProducer.request(LiteProducer.java:240) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.apache.eventmesh.http.demo.AsyncSyncRequestInstance.main(AsyncSyncRequestInstance.java:73) ~[main/:?]
Caused by: com.alibaba.fastjson.JSONException: syntax error,except start with { or [,but actually start with error
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:684) ~[fastjson-1.2.71.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396) ~[fastjson-1.2.71.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:300) ~[fastjson-1.2.71.jar:?]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:573) ~[fastjson-1.2.71.jar:?]
	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:89) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	... 7 more
```

**Comment by Jackzeng1224** [comment]
> @Jackzeng1224 Yes, I can see the log that the message has been sent to kafka.
> You can use `AsyncSyncRequestInstance` to send async requests, and I find a bug in `LiteProducer` line 218.
> https://github.com/apache/incubator-eventmesh/blob/737c0f09efeba61a62653d33fd553491af7d0deb/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/LiteProducer.java#L207-L219
> 
> This method should be async, but it sends a sync command, I will fix in another pr.
> And you can modified the line 218 to
> 
> ```java
> requestParam.addHeader(ProtocolKey.REQUEST_CODE, String.valueOf(RequestCode.MSG_SEND_ASYNC.getRequestCode()))
> ```
> 
> Then you will see below log in runtime module:
> 
> ```
> 2021-07-27 19:28:37,824 INFO  [kafka-producer-network-thread | producer-1] message(SendAsyncMessageProcessor.java:196) - message|eventMesh2mq|REQ|ASYNC|send2MQCost=4ms|topic=TEST-TOPIC-TCP-ASYNC|bizSeqNo=920594188447336930612967879404|uniqueId=243186356065686374194669481534
> ```
> 
> But the response in `AsyncSyncRequestInstance` is also failed, I think it might be another issue.
> 
> ```java
> 2021-07-27 19:48:40,956 DEBUG [main] AsyncSyncRequestInstance(AsyncSyncRequestInstance.java:81) - sendmsg failed
> org.apache.eventmesh.common.EventMeshException: com.alibaba.fastjson.JSONException: syntax error,except start with { or [,but actually start with error
> 	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:94) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
> 	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:41) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[httpclient-4.5.2.jar:4.5.2]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.2.jar:4.5.2]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139) ~[httpclient-4.5.2.jar:4.5.2]
> 	at org.apache.eventmesh.client.http.http.HttpUtil.post(HttpUtil.java:149) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
> 	at org.apache.eventmesh.client.http.producer.LiteProducer.request(LiteProducer.java:240) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
> 	at org.apache.eventmesh.http.demo.AsyncSyncRequestInstance.main(AsyncSyncRequestInstance.java:73) ~[main/:?]
> Caused by: com.alibaba.fastjson.JSONException: syntax error,except start with { or [,but actually start with error
> 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:684) ~[fastjson-1.2.71.jar:?]
> 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396) ~[fastjson-1.2.71.jar:?]
> 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:300) ~[fastjson-1.2.71.jar:?]
> 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:573) ~[fastjson-1.2.71.jar:?]
> 	at org.apache.eventmesh.client.http.producer.RRCallbackResponseHandlerAdapter.handleResponse(RRCallbackResponseHandlerAdapter.java:89) ~[eventmesh-sdk-java-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
> 	... 7 more
> ```


OK！I will continue to pay attention.

**Comment by qqeasonchen** [comment]
@ruanwenjun Could you please submmit this feature to branch kafka-connector?

**Comment by ruanwenjun** [comment]
> @ruanwenjun Could you please submmit this feature to branch kafka-connector?

OK

**Comment by ruanwenjun** [comment]
@Jackzeng1224 Hi, I have updated the code, please help me test, thanks.
Currently, it just supports the async send message method as the same withe rocketmqProducer, so you can just use the publish method to send message.

**Comment by Jackzeng1224** [comment]
> @Jackzeng1224 Hi, I have updated the code, please help me test, thanks.
> Currently, it just supports the async send message method as the same withe rocketmqProducer, so you can just use the publish method to send message.

OK 👌.

**Comment by Jackzeng1224** [comment]
@ruanwenjun   hello,The latest code, I run SpringBootDemoApplication and an exception occurs. I think it is a package usage problem.I use rocketMq will not appear.
image

**Comment by Jackzeng1224** [comment]
@ruanwenjun  hello,New code, still did not solve the problem.

**Comment by ruanwenjun** [comment]
@Jackzeng1224 I don't have this problem, could you please clean the local cache, and start again.

**Comment by xwm1992** [comment]
Since the PR's code has not been updated for a long time, I will close this PR.

**Pull request closed without merging**
