### PR TITLE
[ISSUE #939]Darwin operating system detection bug fix

### PR DESCRIPTION
**Pull request by mytang0**
Fixed #916

### CODE REVIEW

**Comment by Alonexc** [comment]
> _ No description provided. _
Welcome to eventMesh,some checks failed, please check the license, please describe this PR in detail.

**Comment by qqeasonchen** [comment]
@mytang0 A issue associated with this pr is needed, please add it.

**Review by xwm1992 — APPROVED** [review]
LGTM

**Comment by kirinzhu** [comment]
Have created a new issue and associated this with your pr, thank you for your contribution :) @mytang0

**Pull request merged**
